### ISSUE TITLE
errors in case format-security is enabled

### ISSUE THREAD

**Issue by bl00dy1837** [tarjanm-movidius/cutmp3#1]
Hi there thank you for this piece of software.

At archlinux format-security is enabled by default.

`ain.c: In function ‘savesel’:
main.c:2139:9: error: format not a string literal and no format arguments [-Werror=format-security]
 2139 |         if (forced_file==1) snprintf (outname, FN_LEN-1, forcedname);
      |         ^~
main.c: In function ‘savewithtag’:
main.c:2273:60: error: format not a string literal and no format arguments [-Werror=format-security]
 2273 |         if (strlen(title)>0) {hastag=1; snprintf(title1,31,title);} /* check if selection has tag v1 */
      |                                                            ^~~~~
main.c:2276:60: error: format not a string literal and no format arguments [-Werror=format-security]
 2276 |         if (strlen(title)>0) {hasid3=1; snprintf(title2,31,title);} /* check if selection has tag v2 */
      |                                                            ^~~~~
main.c:2316:103: error: format not a string literal and no format arguments [-Werror=format-security]
 2316 |    zaptitle(); importid3v1(filesize); if (strlen(title)>0) {hastag=1; snprintf(title1,31,title);}
      |                                                                                          ^~~~~

main.c:2317:110: error: format not a string literal and no format arguments [-Werror=format-security]
 2317 | itle(); length=importid3v2(0);        if (strlen(title)>0) {hasid3=1; snprintf(title2,31,title);}
      |                                                                                          ^~~~~

main.c:2351:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2351 |                 snprintf (outname, FN_LEN-1, forcedname);
      |                 ^~~~~~~~
main.c:2405:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2405 |                 if (strlen(tmp)>0) {snprintf(temptitle,31,tmp);}
      |                 ^~
main.c:2406:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2406 |                 else snprintf(tmp,31,temptitle); /* recycle old title name when hitting ENTER */
      |                 ^~~~
main.c:2408:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2408 |                 fprintf(outfile,tmp);
      |                 ^~~~~~~
main.c:2415:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2415 |                 if (strlen(tmp)>0) {snprintf(tempartist,31,tmp);}
      |                 ^~
main.c:2416:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2416 |                 else snprintf(tmp,31,tempartist); /* recycle old artist name when hitting ENTER */
      |                 ^~~~
main.c:2418:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2418 |                 fprintf(outfile,tmp);
      |                 ^~~~~~~
main.c:2425:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2425 |                 if (strlen(tmp)>0) {snprintf(tempalbum,31,tmp);}
      |                 ^~
main.c:2426:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2426 |                 else snprintf(tmp,31,tempalbum); /* recycle old album name when hitting ENTER */
      |                 ^~~~
main.c:2428:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2428 |                 fprintf(outfile,tmp);
      |                 ^~~~~~~
main.c:2435:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2435 |                 if (strlen(tmp)>0) {snprintf(tempyear,5,tmp);}
      |                 ^~
main.c:2436:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2436 |                 else snprintf(tmp,5,tempyear); /* recycle old year when hitting ENTER */
      |                 ^~~~
main.c:2438:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2438 |                 fprintf(outfile,tmp);
      |                 ^~~~~~~
main.c:2445:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2445 |                 if (strlen(tmp)>0) {snprintf(tempcomment,31,tmp);}
      |                 ^~
main.c:2446:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2446 |                 else snprintf(tmp,31,tempcomment); /* recycle old comment when hitting ENTER */
      |                 ^~~~
main.c:2448:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2448 |                 fprintf(outfile,tmp);
      |                 ^~~~~~~
main.c:2455:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2455 |                 snprintf(title,31,temptitle);
      |                 ^~~~~~~~
main.c:2456:17: error: format not a string literal and no format arguments [-Werror=format-security]
 2456 |                 snprintf(artist,31,tempartist);
      |                 ^~~~~~~~
main.c:2490:9: error: format not a string literal and no format arguments [-Werror=format-security]
 2490 |         if (forced_file==1) snprintf (newname, FN_LEN-1, forcedname);
      |         ^~
main.c: In function ‘writetable’:
main.c:2676:9: error: format not a string literal and no format arguments [-Werror=format-security]
 2676 |         fprintf(tblfile, userin);
      |         ^~~~~~~
main.c:2678:9: error: format not a string literal and no format arguments [-Werror=format-security]
 2678 |         fprintf(tblfile, userout);
      |         ^~~~~~~
main.c: In function ‘main’:
main.c:2980:41: error: format not a string literal and no format arguments [-Werror=format-security]
 2980 |                                         if (optarg!=0) snprintf(prefix,FN_LEN-1,optarg);
      |                                         ^~
main.c: In function ‘nextframe’:
main.c:439:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  439 |         fread(hdrbuf, 1, 4, mp3file);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c:466:17: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  466 |                 fread(hdrbuf, 1, 4, mp3file);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘prevframe’:
main.c:488:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  488 |         fread(hdrbuf, 1, 4, mp3file);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘avbitrate’:
main.c:737:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  737 |                         fread(&hdrbuf[1], 1, 3, mp3file);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘importid3v2’:
main.c:1140:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1140 |         fread(id3v2, 1, length, mp3file);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘importid3v1’:
main.c:1538:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1538 |         fgets(title,31,mp3file); /* save title */
      |         ^~~~~~~~~~~~~~~~~~~~~~~
main.c:1540:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1540 |         fgets(artist,31,mp3file); /* save artist */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
main.c:1542:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1542 |         fgets(album,31,mp3file); /* save album */
      |         ^~~~~~~~~~~~~~~~~~~~~~~
main.c:1544:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1544 |         fgets(year,5,mp3file); /* save year */
      |         ^~~~~~~~~~~~~~~~~~~~~
main.c:1545:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1545 |         fgets(comment,31,mp3file); /* save comment */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘playsel’:
main.c:1840:17: warning: ignoring return value of ‘system’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1840 |                 system(command);  /* play mp3 excerpt */
      |                 ^~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make: *** [Makefile:14: all] Error 1
`

**Comment by tarjanm-movidius** [comment]
Hey there,
Thank you for reporting it. I've quick-fixed it and created a release (v3.0.3). Will upstream them to v4 I've been working on for a while, but that's a way away still.
